version: '3.1'

services:
  node:
    image: node:18-alpine
    command: sleep infinity

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./shared/redis:/var/lib/redis/data
# Server Api -------------------------------------------------------------------
  homeLabApi:
    depends_on:
      - node
      # - postgres
      - redis
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn start:prod"
    ports:
      - 7001:7001
    working_dir: /HomeLab-ai-api
    volumes:
      - ../HomeLab-ai-api:/HomeLab-ai-api
    environment:
      - PORT=7001
  home4HopeApi:
    depends_on:
      - node
      # - postgres
      - redis
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn migration:run && yarn start:prod"
    ports:
      - 8001:8001
    working_dir: /Home4Hope-api
    volumes:
      - ../Home4Hope-api:/Home4Hope-api
    environment:
      - PORT=8001

  homeLivApi:
    depends_on:
      - node
      # - postgres
      - redis
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn migration:run && yarn start:prod"
    ports:
      - 9001:9001
    working_dir: /HomeLiv-api
    volumes:
      - ../HomeLiv-api:/HomeLiv-api
    environment:
      - PORT=9001

  homeJobApi:
    depends_on:
      - node
    image: node:18-alpine
    command: sh -c "yarn install && cp .production.env .env && yarn build && yarn migration:run && yarn start:prod"
    ports:
      - 6001:6001
    working_dir: /HomeJob-api
    volumes:
      - ../HomeJob-api:/HomeJob-api
    environment:
      - PORT=6001
  homeJob:
    depends_on:
      - node
    image: node:18-alpine
    command: sh -c "yarn install && cp .production.env .env && yarn build && yarn start"
    ports:
      - 3001:3001
    working_dir: /HomeJob
    volumes:
      - ../HomeJob:/HomeJob
    environment:
      - NEXT_PUBLIC_BACKEND_URL=api.homejob.passgenix.com
      - NEXT_PUBLIC_FRONTEND_URL=homejob.passgenix.com
      - NEXT_PUBLIC_PORT=3001
# Server Api -------------------------------------------------------------------
# Client -----------------------------------------------------------------------
  landingPage: 
    depends_on:
      - node
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn start:prod"
    ports:
      - 1001:1001
    working_dir: /landing-page
    volumes:
      - ../landing-page:/landing-page
    environment:
      - PORT=1001

  homeLabPage: 
    depends_on:
      - node
    image: node:18-alpine
    command: sh -c "yarn install && yarn build && yarn start:prod"
    ports:
      - 2001:2001
    working_dir: /home-lab-ai 
    volumes:
      - ../home-lab-ai:/home-lab-ai 
    environment:
      - PORT=2001
# Client -----------------------------------------------------------------------
  
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./shared/postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres: 
  redis:
    
